/*
 * Agent Protocol
 *
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAgentTask404Response {
	/// Message stating the entity was not found
	#[serde(rename = "message")]
	pub message: String,
}

impl GetAgentTask404Response {
	pub fn new(message: String) -> GetAgentTask404Response {
		GetAgentTask404Response { message }
	}
}
