use serde_derive::{Serialize, Deserialize};

/*
 * Agent Protocol
 *
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskListResponse {
    #[serde(rename = "tasks")]
    pub tasks: Vec<crate::models::Task>,
    #[serde(rename = "pagination")]
    pub pagination: Box<crate::models::Pagination>,
}

impl TaskListResponse {
    pub fn new(
        tasks: Vec<crate::models::Task>,
        pagination: crate::models::Pagination,
    ) -> TaskListResponse {
        TaskListResponse {
            tasks,
            pagination: Box::new(pagination),
        }
    }
}
