/*
 * Agent Protocol
 *
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskArtifactsListResponse {
    #[serde(rename = "artifacts")]
    pub artifacts: Vec<crate::models::Artifact>,
    #[serde(rename = "pagination")]
    pub pagination: Box<crate::models::Pagination>,
}

impl TaskArtifactsListResponse {
    pub fn new(
        artifacts: Vec<crate::models::Artifact>,
        pagination: crate::models::Pagination,
    ) -> TaskArtifactsListResponse {
        TaskArtifactsListResponse {
            artifacts,
            pagination: Box::new(pagination),
        }
    }
}
