# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-08-07T12:14:43+00:00

from __future__ import annotations

from fastapi import FastAPI

from agent_protocol.db import NotFoundException
from agent_protocol.middlewares import not_found_exception_handler

app = FastAPI(
    title="Agent Communication Protocol",
    description="Specification of the API protocol for communication with an agent.",
    version="v0.3",
)

app.add_exception_handler(NotFoundException, not_found_exception_handler)


from fastapi.middleware.cors import CORSMiddleware


origins = [
    "http://localhost.tiangolo.com",
    "https://localhost.tiangolo.com",
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:8080",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)