# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-07-13T03:26:56+00:00

from __future__ import annotations

from fastapi import FastAPI

from .routers import actions, state

app = FastAPI(
    title='Agent API',
    description='API for interacting with Agent',
    version='v1',
)

app.include_router(actions.router)
app.include_router(state.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
