[tool.poetry]
name = "agent-protocol"
version = "0.2.0"
description = "API for interacting with Agent"
authors = ["e2b <hello@e2b.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://e2b.dev/"
repository = "https://github.com/e2b-dev/sdk/tree/main/agent/python/"
packages = [{ include = "agent_protocol" }]

[tool.poetry.dependencies]
python = ">=3.7, <4.0.0"
fastapi = "^0.100.0"
hypercorn = "^0.14.4"
pytest = "^7.4.0"
pydantic = "^1.10.5, <2"
click = "^8.1.6"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
fastapi-code-generator = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
agent-protocol = "agent_protocol.cli:cli"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/e2b-dev/agent-protocol/issues"
