/* tslint:disable */
/* eslint-disable */
/**
 * Agent Protocol
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Body of the task request.
 * @export
 * @interface TaskRequestBody
 */
export interface TaskRequestBody {
  /**
   * Input prompt for the task.
   * @type {string}
   * @memberof TaskRequestBody
   */
  input?: string | null
  /**
   * Input parameters for the task. Any value is allowed.
   * @type {object}
   * @memberof TaskRequestBody
   */
  additionalInput?: object
}

/**
 * Check if a given object implements the TaskRequestBody interface.
 */
export function instanceOfTaskRequestBody(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function TaskRequestBodyFromJSON(json: any): TaskRequestBody {
  return TaskRequestBodyFromJSONTyped(json, false)
}

export function TaskRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TaskRequestBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    input: !exists(json, 'input') ? undefined : json['input'],
    additionalInput: !exists(json, 'additional_input')
      ? undefined
      : json['additional_input'],
  }
}

export function TaskRequestBodyToJSON(value?: TaskRequestBody | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    input: value.input,
    additional_input: value.additionalInput,
  }
}
