# generated by fastapi-codegen:
#   filename:  ../openapi.yml
#   timestamp: 2023-07-19T00:16:44+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class AgentTaskInput(BaseModel):
    __root__: Any = Field(
        ..., description='Input parameters for the task. Any value is allowed.'
    )


class AgentArtifact(BaseModel):
    __root__: Any = Field(
        ..., description='Artifact that the task has produced. Any value is allowed.'
    )


class AgentStepInput(BaseModel):
    __root__: Any = Field(
        ..., description='Input parameters for the task step. Any value is allowed.'
    )


class AgentStepOutput(BaseModel):
    __root__: Any = Field(
        ..., description='Output that the task step has produced. Any value is allowed.'
    )


class AgentTaskRequestBody(BaseModel):
    input: Optional[AgentTaskInput] = None


class AgentTask(AgentTaskRequestBody):
    task_id: str = Field(..., description='The ID of the task.')
    artifacts: List[AgentArtifact] = Field(
        ..., description='A list of artifacts that the task has produced.'
    )


class AgentStepRequestBody(BaseModel):
    input: Optional[AgentStepInput] = None


class AgentStepResult(BaseModel):
    output: Optional[AgentStepOutput] = None
    artifacts: List[AgentArtifact] = Field(
        ..., description='A list of artifacts that the step has produced.'
    )
    is_last: Optional[bool] = Field(
        False, description='Whether this is the last step in the task.'
    )


class AgentStep(AgentStepRequestBody, AgentStepResult):
    task_id: str = Field(..., description='The ID of the task this step belongs to.')
    step_id: str = Field(..., description='The ID of the task step.')
