# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-08-02T09:14:29+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title="Agent Communication Protocol",
    description="Specification of the API protocol for communication with an agent.",
    version="v0.2",
)
