# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-07-19T00:16:44+00:00

from __future__ import annotations

from fastapi import FastAPI

app = FastAPI(
    title="Agent Communication Protocol",
    description="Specification of the API protocol for communication with an agent.",
    version="v1",
)
