# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2023-09-15T22:33:36+00:00

from __future__ import annotations

from fastapi import FastAPI

from agent_protocol.db import NotFoundException
from agent_protocol.middlewares import not_found_exception_handler

app = FastAPI(
    title="Agent Communication Protocol",
    description="Specification of the API protocol for communication with an agent.",
    version="v1",
)

app.add_exception_handler(NotFoundException, not_found_exception_handler)