/* tslint:disable */
/* eslint-disable */
/**
 * Agent Protocol
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface TaskListResponse
 */
export interface TaskListResponse {
    /**
     * 
     * @type {Array<Task>}
     * @memberof TaskListResponse
     */
    tasks: Array<Task>;
    /**
     * 
     * @type {Pagination}
     * @memberof TaskListResponse
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the TaskListResponse interface.
 */
export function instanceOfTaskListResponse(value: object): boolean {
    if (!('tasks' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function TaskListResponseFromJSON(json: any): TaskListResponse {
    return TaskListResponseFromJSONTyped(json, false);
}

export function TaskListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function TaskListResponseToJSON(value?: TaskListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

