# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent_protocol_client.models.step import Step


class TestStep(unittest.TestCase):
    """Step unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Step:
        """Test Step
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Step`
        """
        model = Step()
        if include_optional:
            return Step(
                input = 'Write the words you receive to the file 'output.txt'.',
                additional_input = {
"file_to_refactor": "models.py"
},
                task_id = '50da533e-3904-4401-8a07-c49adf88b5eb',
                step_id = '6bb1801a-fd80-45e8-899a-4dd723cc602e',
                name = 'Write to file',
                status = 'created',
                output = 'I am going to use the write_to_file command and write Washington to a file called output.txt <write_to_file('output.txt', 'Washington')',
                additional_output = {
"tokens": 7894,
"estimated_cost": "0,24$"
},
                artifacts = [
                    agent_protocol_client.models.artifact.Artifact(
                        artifact_id = 'b225e278-8b4c-4f99-a696-8facf19f0e56', 
                        agent_created = False, 
                        file_name = 'main.py', 
                        relative_path = 'python/code/', )
                    ],
                is_last = True
            )
        else:
            return Step(
                task_id = '50da533e-3904-4401-8a07-c49adf88b5eb',
                step_id = '6bb1801a-fd80-45e8-899a-4dd723cc602e',
                status = 'created',
                artifacts = [
                    agent_protocol_client.models.artifact.Artifact(
                        artifact_id = 'b225e278-8b4c-4f99-a696-8facf19f0e56', 
                        agent_created = False, 
                        file_name = 'main.py', 
                        relative_path = 'python/code/', )
                    ],
                is_last = True,
        )
        """

    def testStep(self):
        """Test Step"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
