# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent_protocol_client.models.task_request_body import TaskRequestBody


class TestTaskRequestBody(unittest.TestCase):
    """TaskRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskRequestBody:
        """Test TaskRequestBody
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TaskRequestBody`
        """
        model = TaskRequestBody()
        if include_optional:
            return TaskRequestBody(
                input = 'Write 'Washington' to the file 'output.txt'.',
                additional_input = {
"debug": false,
"mode": "benchmarks"
}
            )
        else:
            return TaskRequestBody(
        )
        """

    def testTaskRequestBody(self):
        """Test TaskRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
