# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent_protocol_client.models.task import Task


class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Task:
        """Test Task
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Task`
        """
        model = Task()
        if include_optional:
            return Task(
                input = 'Write 'Washington' to the file 'output.txt'.',
                additional_input = {
"debug": false,
"mode": "benchmarks"
},
                task_id = '50da533e-3904-4401-8a07-c49adf88b5eb',
                artifacts = ["7a49f31c-f9c6-4346-a22c-e32bc5af4d8e","ab7b4091-2560-4692-a4fe-d831ea3ca7d6"]
            )
        else:
            return Task(
                task_id = '50da533e-3904-4401-8a07-c49adf88b5eb',
                artifacts = ["7a49f31c-f9c6-4346-a22c-e32bc5af4d8e","ab7b4091-2560-4692-a4fe-d831ea3ca7d6"],
        )
        """

    def testTask(self):
        """Test Task"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
