# coding: utf-8

"""
    Agent Protocol

    Specification of the API protocol for communication with an agent.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agent_protocol_client.models.step_request_body import StepRequestBody


class TestStepRequestBody(unittest.TestCase):
    """StepRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StepRequestBody:
        """Test StepRequestBody
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `StepRequestBody`
        """
        model = StepRequestBody()
        if include_optional:
            return StepRequestBody(
                input = 'Write the words you receive to the file 'output.txt'.',
                additional_input = {
"file_to_refactor": "models.py"
}
            )
        else:
            return StepRequestBody(
        )
        """

    def testStepRequestBody(self):
        """Test StepRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
