name: Build JS SDK

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'apps/agentprotocol.ai/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        working-directory: ./apps/agentprotocol.ai/
        run: npm ci

      # - name: Lint
      #   working-directory: ./apps/agentprotocol.ai/
      #   run: npm run lint

      - name: Build
        working-directory: ./apps/agentprotocol.ai/
        run: npm run build
