name: Build and Publish Python SDK Package

on:
  push:
    tags: [python-sdk-v*]

permissions:
  contents: write

jobs:
  publish:
    name: Build and publish the Python package
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./sdk/python/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Build Package
        run: poetry build

      - name: Config Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Publish Package
        run: poetry publish

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
